### PR TITLE
Create simplified Chinese Translation

### PR DESCRIPTION
**Pull request by misaka10843**
Hello, 
first of all, 
thank you very much for making this launcher, 
I feel this launcher is very good (especially the UI), 
but see that you don't seem to have the translation in Simplified Chinese, 
so I translated it for the time being, 
there may be some places still a bit colloquial problem, 
so for the time being can only be set to draft.

----

您好，
首先十分感谢您制作了这个启动器，
我感觉这个启动器非常好（特别是UI），
但是看见您似乎并没有简体中文的翻译，
所以我就暂时翻译了一下，
可能有些地方还有点口语化的问题，
所以暂时只能设置为草案。

### CODE REVIEW

**Review by misaka10843 — COMMENTED** [review]
在加载Api/提示/地区切换中似乎并未使用i18n中的文本（The text in i18n does not seem to be used in the load Api/tips/region switch）
image

程序设置中显示控制台开关似乎并未使用i18n的文本（The program settings show that the console switch does not seem to use the i18n text）
image

**Comment by misaka10843** [comment]
image
在更新界面似乎并没有使用i18n中的文本（The update screen doesn't seem to use the text in i18n）


现阶段只找到了以上的问题，
如果过段时间后没有出现其他问题或者其他需要翻译的地方即可准备合并
（At this stage, only the above problems have been found, and if no other problems or other areas need to be translated after some time, then we can prepare to merge）

**Comment by neon-nyan** [comment]
Hi, Thank you for your contribution on this project.
I will try to review this PR first and will get back to you later 😄

**Comment by neon-nyan** [comment]
Hi there,
I've pushed some commits (including my local commit and fix for some i18n issues as mentioned).
Some changes are included in original localization file. You can use the reference below:

```JSON
  "_Misc": {
    "ApplyingPatch": "Applying Patch",
    "Disabled": "Disabled",
    "Enabled": "Enabled",

    "BuildChannelPreview": "Preview",
    "BuildChannelStable": "Stable"
  },

  "_UpdatePage": {
    "PageTitle1": "UPDATE",
    "PageTitle2": "IS AVAILABLE!",
    "VerCurLabel": "Current Version:",
    "VerNewLabel": "New Version:",
    "VerChannelLabel": "Update Channel:",
    "VerDateLabel": "Compiled on:",
    "ReleaseNote": "Release Notes",
    "NeverShowNotification": "Never show me this update notification again",
    "RemindLaterBtn": "Remind me later",
    "UpdateNowBtn": "Update Now",
    "LoadingRelease": "Loading Release Notes...",
    "LoadingReleaseFailed": "Error while fetching Release Notes.\r\n{0}"
  }
```

For more info, please check [**on this commit**](https://github.com/neon-nyan/CollapseLauncher/commit/1582d97b97a29ef303822334372fb3fdd28d28e3#diff-f3e63ea57f9c24a1cb893d7d4fb3524d75906c708afd8db19bac289b735559b0).

**Review by neon-nyan — CHANGES_REQUESTED** [review]
As per my latest comment, you can add some new translation for the fix on i18n mentioned before.

Here's the additional changes for your reference:
```JSON
  "_Misc": {
    ...
    "ApplyingPatch": "Applying Patch",
    "Disabled": "Disabled",
    "Enabled": "Enabled",

    "BuildChannelPreview": "Preview",
    "BuildChannelStable": "Stable"
  },

  "_UpdatePage": {
    "PageTitle1": "UPDATE",
    "PageTitle2": "IS AVAILABLE!",
    "VerCurLabel": "Current Version:",
    "VerNewLabel": "New Version:",
    "VerChannelLabel": "Update Channel:",
    "VerDateLabel": "Compiled on:",
    "ReleaseNote": "Release Notes",
    "NeverShowNotification": "Never show me this update notification again",
    "RemindLaterBtn": "Remind me later",
    "UpdateNowBtn": "Update Now",
    "LoadingRelease": "Loading Release Notes...",
    "LoadingReleaseFailed": "Error while fetching Release Notes.\r\n{0}"
  }
```

**Comment by misaka10843** [comment]
> Hi, Thank you for your contribution on this project.
> I will try to review this PR first and will get back to you later 😄

Thanks! I will add these to the translation later o(≧▽≦)o

**Comment by neon-nyan** [comment]
Thank you. Looking forward for the progress 😃

**Comment by misaka10843** [comment]
image
I don't know why,
but I can't see other language options in the settings,
only English is in the options, 
and it shows switching to English at startup.

（But I think the updated translation is already OK (although I didn't look at the translated UI)）

**Comment by neon-nyan** [comment]
Don't forget to set the Build Action to "Content" and Copy to Output Directory to "Copy Always" for your translation file in Visual Studio.
You can also try remove the ``AppLanguage`` key in App Config file located here:
```C:\Users\<username>\AppData\LocalLow\CollapseLauncher\config.ini```

On my side, Looks good to me. I think we can merge this PR tomorrow or wait If you have any additional edit for this PR.
Anyway, thank you for the contribution 👍

**Review by neon-nyan — APPROVED** [review]

**Comment by misaka10843** [comment]
> On my side, Looks good to me. I think we can merge this PR tomorrow or wait If you have any additional edit for this PR. Anyway, thank you for the contribution 👍

I think we are ready to merge this PR, and I confirmed that there are no more problems.
Thanks for developing this launcher!( ╹▽╹ )

**Pull request merged**
